export const VERSION_HISTORY = [
  { version: 102, date: '2026-08-06', summary: 'Corrige Lembretes durante viagem: usa a data e hora gravadas no próprio lembrete (fuso do aparelho) em vez de sempre converter para o fuso de São Paulo — resolve horário exibido errado e lembretes de hoje aparecendo como vencidos' },
  { version: 101, date: '2026-07-30', summary: 'Corrige o alinhamento do subcontador do card Geral: agora fica exatamente na mesma altura do número da HubSpot na 1ª linha' },
  { version: 100, date: '2026-07-30', summary: 'Sobe o subcontador do card Geral para o topo, alinhado com os números da 1ª linha, usando a mesma fonte deles' },
  { version: 99, date: '2026-07-30', summary: 'Histórico de Versões todo em português; novo contador (Meu Dia + Lembretes + Notion + HubSpot) acima do Total Geral, dentro da caixa Geral; reordena os quadros de resumo: 1ª linha Meu Dia/Lembretes/Notion/HubSpot, 2ª linha Starting Day/Ending Day/TickTick/Hábitos' },
  { version: 98, date: '2026-07-30', summary: 'Adiciona Histórico de Versões: ao passar o mouse sobre o e-mail e clicar no item do menu, mostra a lista completa de versões com data e descrição de cada uma' },
  { version: 97, date: '2026-07-29', summary: 'Corrige contagem de sequência de hábitos ao pular um dia (agora quebra o streak, como um dia em branco); corrige card de Lembretes recolhendo sozinho a cada atualização em segundo plano' },
  { version: 96, date: '2026-07-25', summary: 'Expande automaticamente um quadro retraído ao clicar em Editar' },
  { version: 95, date: '2026-07-25', summary: 'Torna as células de dia dos Hábitos clicáveis no modo de edição' },
  { version: 94, date: '2026-07-25', summary: 'Adiciona layout responsivo para telas de celular' },
  { version: 93, date: '2026-07-24', summary: 'Adiciona ?forceWeekReset=1 para reforçar manualmente o prompt de reset do Ending Week' },
  { version: 92, date: '2026-07-24', summary: 'Corrige eventos recorrentes do calendário que desapareciam ao mover para outro dia' },
  { version: 91, date: '2026-07-23', summary: 'Corrige o baseline de progresso do dia sendo capturado antes de responder o prompt de reset diário' },
  { version: 90, date: '2026-07-22', summary: 'Reorganizar ordem dos 8 quadros de resumo do cabeçalho' },
  { version: 89, date: '2026-07-21', summary: 'Geral e barra de progresso ficam congelados durante o carregamento (atualizam de uma vez ao terminar); Atualizar tudo agora sincroniza Lembretes de verdade' },
  { version: 88, date: '2026-07-20', summary: 'Corrigir badge que não aparecia após ativar notificações: reemitir setAppBadge assim que a permissão é concedida' },
  { version: 87, date: '2026-07-20', summary: 'Hábitos: adicionar opção de link na edição, abre ao clicar no item' },
  { version: 86, date: '2026-07-20', summary: 'Corrigir bug real: hs_timestamp do HubSpot vem como string ISO, não epoch ms — Number() virava NaN e nada era marcado vencido' },
  { version: 85, date: '2026-07-20', summary: 'DEBUG temporário: expor hs_timestamp bruto e cálculo de vencido nas tarefas HubSpot' },
  { version: 84, date: '2026-07-20', summary: 'HubSpot: vencido considera dia+hora (não só a data); troca selos de texto por emojis 🔴/✅ ao lado do nome do deal' },
  { version: 83, date: '2026-07-20', summary: 'Lembretes: mover itens de hoje já vencidos para Vencidos (fonte vermelha), baseado no horário da última sincronização. HubSpot: fonte vermelha para atrasados, selo verde \'ok\' para tarefas de hoje' },
  { version: 82, date: '2026-07-20', summary: 'Adicionar submenu no e-mail (Exportar dados + Sair) com exportação de backup em JSON' },
  { version: 81, date: '2026-07-20', summary: 'Hábitos inicia retraído, Meu Dia inicia expandido' },
  { version: 80, date: '2026-07-20', summary: 'Hábitos: fonte esmaecida quando marcado/saltado (como Starting Day); reduzir espaçamento das listas' },
  { version: 79, date: '2026-07-20', summary: 'Hábitos: cor pastel vermelho pro saltado, rótulos restaurados, junta HubSpot no resumo e inclui hábitos no total Geral' },
  { version: 78, date: '2026-07-20', summary: 'Hábitos: checkbox único marca o dia de hoje, remove rótulo \'A evitar\', quadradinhos sempre verdes quando feitos' },
  { version: 77, date: '2026-07-20', summary: 'Corrigir tela em branco: mesclar cache local antigo com os defaults da seed antes do primeiro render' },
  { version: 76, date: '2026-07-20', summary: 'Adicionar retrair/expandir no Meu Dia e nova sessão de Hábitos (bons e a evitar) com sequência de 7 dias, edição e contadores' },
  { version: 75, date: '2026-07-19', summary: 'Desfazer v74; aplicar fonte do Agenda de Hoje nos títulos do resumo do topo' },
  { version: 74, date: '2026-07-19', summary: 'Unificar fonte dos títulos dos cards com o padrão do Agenda de Hoje' },
  { version: 73, date: '2026-07-19', summary: 'Só usar x-success (retorno automático) no iOS; evita aba extra do Chrome no Mac' },
  { version: 72, date: '2026-07-19', summary: 'Corrigir loop infinito do auto-sync de Lembretes ao voltar do Atalho em janela nova' },
  { version: 71, date: '2026-07-19', summary: 'Remover instrumentação de debug do badge; ocultar botão de notificações quando já concedida' },
  { version: 70, date: '2026-07-19', summary: 'Pedir permissão de notificação via toque no botão (iOS exige gesto do usuário)' },
  { version: 69, date: '2026-07-19', summary: 'Solicitar permissão de notificação para destravar badge no iOS' },
  { version: 68, date: '2026-07-19', summary: 'Diagnóstico do badge agora ignora a chamada inicial de clear' },
  { version: 67, date: '2026-07-19', summary: 'Diagnóstico temporário do badge do app' },
  { version: 66, date: '2026-07-19', summary: 'Mensagem de carregamento fica verde e maior' },
  { version: 65, date: '2026-07-19', summary: 'Adiciona mensagem \'Carregando informações...\' entre a data e o horário' },
  { version: 64, date: '2026-07-19', summary: 'Corrige captura do baseline saindo antes do Notion terminar' },
  { version: 63, date: '2026-07-19', summary: 'Corrige o baseline capturado antes da sincronização de Lembretes terminar' },
  { version: 62, date: '2026-07-19', summary: 'Remove o gate das 17:30 do Ending Day no Geral' },
  { version: 61, date: '2026-07-19', summary: 'Adiciona gatilho manual ?forceReset=1 pra reforçar reset e baseline' },
  { version: 60, date: '2026-07-18', summary: 'Remove o total do Starting Day e Ending Day no resumo' },
  { version: 59, date: '2026-07-18', summary: 'Preenchimento da barra de progresso passa a ser verde' },
  { version: 58, date: '2026-07-18', summary: 'Reinicia a checklist \'Ending Week\' toda sexta às 14h' },
  { version: 57, date: '2026-07-18', summary: 'Adiciona checklist \'Ending Week\' na segunda coluna' },
  { version: 56, date: '2026-07-18', summary: 'Aumenta o anel e a fonte do percentual no card Geral' },
  { version: 55, date: '2026-07-18', summary: 'Adiciona anel de progresso dentro do card Geral' },
  { version: 54, date: '2026-07-18', summary: 'Restringe a barra de progresso ao bloco de resumo do Hoje' },
  { version: 53, date: '2026-07-18', summary: 'Corrige o layout quebrado da barra de progresso do dia' },
  { version: 52, date: '2026-07-18', summary: 'Move a barra de progresso do dia para logo abaixo do resumo' },
  { version: 51, date: '2026-07-18', summary: 'Torna a barra de progresso do dia sempre visível e mais robusta' },
  { version: 50, date: '2026-07-18', summary: 'Adiciona barra de progresso do dia, fixa no rodapé' },
  { version: 49, date: '2026-07-18', summary: 'Sincroniza Lembretes ao abrir o dashboard, cor de atraso e reorganiza o resumo' },
  { version: 48, date: '2026-07-18', summary: 'Faz o refresh dos Lembretes reagir sozinho após o Atalho terminar' },
  { version: 47, date: '2026-07-18', summary: 'Consolida sincronizar+atualizar dos Lembretes, ajusta títulos e remove refresh do Meu Dia' },
  { version: 46, date: '2026-07-18', summary: 'Consolida os dois blocos de Lembretes em um só, agrupado' },
  { version: 45, date: '2026-07-18', summary: 'Links do Hubspot apontam para as views \'Meu Dia\' e \'Sem tarefa\' (Board)' },
  { version: 44, date: '2026-07-18', summary: 'Links do Hubspot abrem em nova aba, remove indicador ✅ do cabeçalho' },
  { version: 43, date: '2026-07-18', summary: 'Limpa dados ao atualizar e adiciona link Hubspot nos blocos de tarefas/deals' },
  { version: 42, date: '2026-07-18', summary: 'TickTick: link da tarefa tenta abrir no app (ticktick://) em vez do navegador' },
  { version: 41, date: '2026-07-18', summary: 'TickTick: inclui a Caixa de Entrada (via id especial "inbox") no bloco de tarefas, e limpa a instrumentação de debug já resolvida' },
  { version: 40, date: '2026-07-18', summary: 'TickTick debug: testa o id especial "inbox" para a Caixa de Entrada, que não aparece na listagem normal de projetos' },
  { version: 39, date: '2026-07-18', summary: 'TickTick debug: testa parâmetro de limite/paginação para confirmar se os 99 itens são um teto rígido da API' },
  { version: 38, date: '2026-07-18', summary: 'TickTick debug: conta quantas tarefas passam em cada filtro e permite buscar uma tarefa específica por título' },
  { version: 37, date: '2026-07-18', summary: 'TickTick: adiciona modo debug para inspecionar dados brutos de um projeto específico' },
  { version: 36, date: '2026-07-18', summary: 'Erro de configuração do callback do TickTick agora lista exatamente quais variáveis de ambiente estão faltando' },
  { version: 35, date: '2026-07-18', summary: 'Adiciona integração real com TickTick (OAuth2, tarefas vencidas/hoje agrupadas por lista, botão do app, contrair/expandir) e generaliza o card de tarefas agrupadas para Notion + TickTick' },
  { version: 34, date: '2026-07-18', summary: 'Perguntar antes de reiniciar Starting Day/Ending Day no primeiro carregamento do dia' },
  { version: 33, date: '2026-07-18', summary: 'Notion: agrupar tarefas usando a relação reversa da base Projetos ("[A] Atividades"), já que a relação direta da tarefa é pouco confiável via API' },
  { version: 32, date: '2026-07-18', summary: 'Debug: inspecionar diretamente a base Projetos (schema + amostra), já que a propriedade não pertence ao schema da base de tarefas' },
  { version: 31, date: '2026-07-18', summary: 'Debug: corrige comparação de schema por nome em vez de id (o id vinha em formatos diferentes entre os dois endpoints), com dump de todos os tipos como rede de segurança' },
  { version: 30, date: '2026-07-18', summary: 'Debug: incluir a definição do schema da propriedade de projeto (detecta relação sincronizada/dual-property)' },
  { version: 29, date: '2026-07-18', summary: 'Debug: permite escolher a tarefa testada via ?title= em vez de sempre a primeira' },
  { version: 28, date: '2026-07-18', summary: 'Debug: expor status/corpo cru da chamada de property item, em vez de engolir o erro silenciosamente' },
  { version: 27, date: '2026-07-18', summary: 'Notion: buscar o valor real da relação de projeto via endpoint dedicado, já que a query de database não retorna esse dado de forma confiável' },
  { version: 26, date: '2026-07-18', summary: 'Notion: modo debug agora rastreia a resolução completa do item principal (parent fallback) para diagnosticar o grupo "Sem Projeto"' },
  { version: 25, date: '2026-07-18', summary: 'Notion: agrupar tarefas por projeto (ordenado A-Z, tarefas A-Z dentro do grupo), como no bloco HubSpot; corrige filtro de data (comparação de calendário em vez de instante, evitando tarefas de amanhã aparecerem como vencidas)' },
  { version: 24, date: '2026-07-18', summary: 'Notion: busca o projeto no item principal quando o subitem não tem a relação diretamente' },
  { version: 23, date: '2026-07-18', summary: 'Renomeia botão da Agenda para "Calendário", corrige exclusão de status por gênero (Concluída/Cancelada), busca tolerante de propriedade Status, e adiciona modo debug ao endpoint do Notion' },
  { version: 22, date: '2026-07-18', summary: 'Corrige sufixo de projeto (relação) e link do Notion (abre no app), reduz fonte dos subtítulos do HubSpot, corrige edição do Meu Dia (cursor no meio do texto, tamanho sem salto) e adiciona cor cinza' },
  { version: 21, date: '2026-07-18', summary: 'Ajustes no bloco Notion: link posicionado na view Hoje, botão renomeado, título com hierarquia visual, e resolução de projeto via relação' },
  { version: 20, date: '2026-07-18', summary: 'Notion: botão para abrir a visão semanal no app, painel recolhível (inicia retraído), e sufixo [A] Projetos; Meu Dia: seletor de cor por post-it' },
  { version: 19, date: '2026-07-18', summary: 'Renomear bloco Notion e abrir tarefas em nova aba sem tirar o foco do dashboard' },
  { version: 18, date: '2026-07-18', summary: 'Corrigir título em branco nas tarefas do Notion (fallback para a propriedade real de título)' },
  { version: 17, date: '2026-07-18', summary: 'Excluir tarefas Concluído/Cancelado do bloco Notion - Hoje' },
  { version: 16, date: '2026-07-18', summary: 'Adicionar bloco Notion - Hoje com dados reais (vencidas + hoje, com hyperlink)' },
  { version: 15, date: '2026-07-18', summary: 'Adicionar botão de editar nota no Meu Dia, ao lado do X' },
];
