export const VERSION_HISTORY = [
  { version: 130, date: '2026-10-02', summary: 'Saúde: gráfico de sono (30 noites, duração e fases profundo/essencial/REM/acordado) ao lado do peso, vindo do app Saúde pelo atalho; cabeçalho passa a mostrar Sono, Dormiu e Acordou da última noite. Peso: linha vermelha do peso atual agora contínua e nova linha azul no menor peso do período' },
  { version: 129, date: '2026-10-02', summary: 'Peso: médias móveis tracejadas e mais suaves, liga/desliga lembrado entre aberturas, cabeçalho do gráfico numa linha só, datas do eixo em intervalos fixos (dia 1 de cada mês no 365d/Geral), linha vermelha tracejada no peso atual, variação do período em verde (desceu) ou vermelho (subiu); sai a contagem de registros' },
  { version: 128, date: '2026-10-02', summary: 'Saúde: gráfico do peso em meia largura, médias móveis de 7d e 30d com botão de liga/desliga ao lado dos filtros, rodapé com o peso do primeiro dia do período e a variação. Cabeçalho da Saúde refeito com 8 itens na fonte do Hoje: Peso (com setas de 7/30/90 dias), IAH, Sono, Qualidade, Dormiu, Acordou, Passos e Exercício' },
  { version: 127, date: '2026-10-02', summary: 'Nova aba Saúde: gráfico de peso vindo do app Saúde da Apple (atalho "Sincronizar Saúde" no iPhone) com filtros 7d/30d/90d/365d/Geral, médias móveis de 7 e 30 dias e setas de tendência; painel de IAH do CPAP com registro manual e gráfico de 30 dias. Hábitos, peso manual, sono da semana e metas da semana saíram da aba' },
  { version: 126, date: '2026-10-02', summary: 'Agenda sempre abre no dia de hoje ao abrir o dashboard, mesmo que tenha ficado em "amanhã" na sessão anterior' },
  { version: 125, date: '2026-10-01', summary: 'Notion: quando o erro é do lado deles (500/429), o card mostra uma mensagem clara ("o Notion está fora do ar no momento…") em vez do JSON cru da API' },
  { version: 124, date: '2026-10-01', summary: 'Notion: erros temporários do servidor deles (500, 429) agora são tentados de novo automaticamente até 3 vezes antes de mostrar "Não deu pra carregar"' },
  { version: 123, date: '2026-09-27', summary: 'Setinha ▾ e botão ⟳ do dólar maiores e na mesma cor da data da cotação; "atualizado às" só muda ao abrir o dashboard ou em "Atualizar tudo" — refreshes de painéis isolados (ex.: dólar de hora em hora) não mexem mais nele' },
  { version: 122, date: '2026-09-27', summary: 'Box do dólar: data (dd/mm) e hora da última atualização da cotação embaixo da variação %; cotação passa a se atualizar sozinha de hora em hora' },
  { version: 121, date: '2026-09-26', summary: 'Versão do dashboard alinha pela esquerda com "atualizado às" (antes era pela direita); e-mail passa a ficar à direita da versão em vez de antes dela' },
  { version: 120, date: '2026-09-26', summary: 'Corrige coluna direita do cabeçalho: faltava alinhar o grid inteiro à borda direita (só o conteúdo de cada célula estava alinhado), deixando "atualizado às"/versão/e-mail flutuando longe da borda em vez de coladas nela como antes' },
  { version: 119, date: '2026-09-26', summary: 'Gráfico do dólar: período padrão vira 7 dias; Mínimo e Máximo da janela aparecem ao lado da cotação inicial; versão do dashboard move pra linha do e-mail, alinhada embaixo de "atualizado às" (grid de 3 colunas no lugar de duas linhas soltas)' },
  { version: 117, date: '2026-09-26', summary: 'Cabeçalho: "Carregando informações" menor, debaixo do e-mail; box do dólar centralizado de verdade entre a data e a versão; refresh embutido no box; popover do dólar com fonte real (Yahoo, clicável), tooltip no gráfico ao passar o mouse, cotação sob a data inicial, e sem mais "Variação no período"' },
  { version: 115, date: '2026-09-26', summary: 'Cotação do dólar: AwesomeAPI dava 429 em toda chamada vinda da Vercel; troca pra fonte oficial do Banco Central (PTAX), sem rate limit e mais legítima como fonte' },
  { version: 114, date: '2026-09-26', summary: 'Cotação do dólar: cache no edge da Vercel não funcionava (deployment protection desativa cache), troca pra cache real no Supabase (usd_quote_cache) — precisa criar a tabela, ver instrução' },
  { version: 113, date: '2026-09-25', summary: 'Corrige cotação do dólar não carregando (429 da AwesomeAPI): resposta agora fica em cache no edge da Vercel por 5min, reduzindo as chamadas reais à API e evitando o rate limit' },
  { version: 112, date: '2026-09-25', summary: 'Adiciona cotação do dólar no cabeçalho, ao lado da data: variação do dia + popover com gráfico e % de 7d/30d/90d/365d (fonte: AwesomeAPI — UOL bloqueia scraping via WAF). Atualiza só ao abrir o dash, no botão de refresh ou no "Atualizar tudo"' },
  { version: 111, date: '2026-09-25', summary: 'Lembretes: sync com o Atalho continua tentando por até 45s (antes parava em 15s) — com muitos lembretes o loop do Atalho pode demorar mais que isso pra terminar e postar os dados filtrados' },
  { version: 110, date: '2026-09-25', summary: 'HubSpot - Deals sem Tarefa: exclui deals nos estágios Inbox e Contato Quente, além dos já excluídos' },
  { version: 109, date: '2026-09-18', summary: 'Cards do resumo (Meu Dia, Lembretes, Notion, HubSpot, Starting/Ending Day, TickTick, Hábitos) ganham contorno verde de 3px + selo de check quando o bloco zera' },
  { version: 108, date: '2026-09-18', summary: 'Hábitos: remove a linha extra do cabeçalho de dias da semana — agora ele fica na mesma linha do título do grupo (à direita, acima dos quadradinhos), sem espaço em branco entre o título e o primeiro hábito' },
  { version: 107, date: '2026-09-18', summary: 'Hábitos: contador fica colado ao lado do título de cada grupo (Diários/A Evitar), e o cabeçalho com a letra do dia da semana repete acima dos quadradinhos de cada grupo, bem mais próximo deles' },
  { version: 106, date: '2026-09-18', summary: 'Ending Week agora reinicia em qualquer horário de sexta-feira (não só depois das 14h); bloco de Hábitos ganha um cabeçalho com a letra do dia da semana acima dos quadradinhos' },
  { version: 105, date: '2026-08-21', summary: 'Remove a barra "Progresso do dia" do cabeçalho; o card Geral (anel de % + total) fica no lugar dela. O painel de Saúde ao lado agora acompanha a altura do bloco Hoje automaticamente' },
  { version: 104, date: '2026-08-21', summary: 'Adiciona "Reiniciar dia" ao menu de conta: pergunta se quer zerar as checklists Starting Day/Ending Day e refaz o baseline de progresso do dia com o total atual, como se fosse a primeira abertura do dia' },
  { version: 103, date: '2026-08-21', summary: 'Menu de conta agora abre por um botão (☰) ao lado do e-mail em vez de passar o mouse; número da versão sobe para o topo, ao lado de "atualizado às"' },
  { version: 102, date: '2026-08-06', summary: 'Corrige Lembretes durante viagem: usa a data e hora gravadas no próprio lembrete (fuso do aparelho) em vez de sempre converter para o fuso de São Paulo — resolve horário exibido errado e lembretes de hoje aparecendo como vencidos' },
  { version: 101, date: '2026-07-30', summary: 'Corrige o alinhamento do subcontador do card Geral: agora fica exatamente na mesma altura do número da HubSpot na 1ª linha' },
  { version: 100, date: '2026-07-30', summary: 'Sobe o subcontador do card Geral para o topo, alinhado com os números da 1ª linha, usando a mesma fonte deles' },
  { version: 99, date: '2026-07-30', summary: 'Histórico de Versões todo em português; novo contador (Meu Dia + Lembretes + Notion + HubSpot) acima do Total Geral, dentro da caixa Geral; reordena os quadros de resumo: 1ª linha Meu Dia/Lembretes/Notion/HubSpot, 2ª linha Starting Day/Ending Day/TickTick/Hábitos' },
  { version: 98, date: '2026-07-30', summary: 'Adiciona Histórico de Versões: ao passar o mouse sobre o e-mail e clicar no item do menu, mostra a lista completa de versões com data e descrição de cada uma' },
  { version: 97, date: '2026-07-29', summary: 'Corrige contagem de sequência de hábitos ao pular um dia (agora quebra o streak, como um dia em branco); corrige card de Lembretes recolhendo sozinho a cada atualização em segundo plano' },
  { version: 96, date: '2026-07-25', summary: 'Expande automaticamente um quadro retraído ao clicar em Editar' },
  { version: 95, date: '2026-07-25', summary: 'Torna as células de dia dos Hábitos clicáveis no modo de edição' },
  { version: 94, date: '2026-07-25', summary: 'Adiciona layout responsivo para telas de celular' },
  { version: 93, date: '2026-07-24', summary: 'Adiciona ?forceWeekReset=1 para reforçar manualmente o prompt de reset do Ending Week' },
  { version: 92, date: '2026-07-24', summary: 'Corrige eventos recorrentes do calendário que desapareciam ao mover para outro dia' },
  { version: 91, date: '2026-07-23', summary: 'Corrige o baseline de progresso do dia sendo capturado antes de responder o prompt de reset diário' },
  { version: 90, date: '2026-07-22', summary: 'Reorganizar ordem dos 8 quadros de resumo do cabeçalho' },
  { version: 89, date: '2026-07-21', summary: 'Geral e barra de progresso ficam congelados durante o carregamento (atualizam de uma vez ao terminar); Atualizar tudo agora sincroniza Lembretes de verdade' },
  { version: 88, date: '2026-07-20', summary: 'Corrigir badge que não aparecia após ativar notificações: reemitir setAppBadge assim que a permissão é concedida' },
  { version: 87, date: '2026-07-20', summary: 'Hábitos: adicionar opção de link na edição, abre ao clicar no item' },
  { version: 86, date: '2026-07-20', summary: 'Corrigir bug real: hs_timestamp do HubSpot vem como string ISO, não epoch ms — Number() virava NaN e nada era marcado vencido' },
  { version: 85, date: '2026-07-20', summary: 'DEBUG temporário: expor hs_timestamp bruto e cálculo de vencido nas tarefas HubSpot' },
  { version: 84, date: '2026-07-20', summary: 'HubSpot: vencido considera dia+hora (não só a data); troca selos de texto por emojis 🔴/✅ ao lado do nome do deal' },
  { version: 83, date: '2026-07-20', summary: 'Lembretes: mover itens de hoje já vencidos para Vencidos (fonte vermelha), baseado no horário da última sincronização. HubSpot: fonte vermelha para atrasados, selo verde \'ok\' para tarefas de hoje' },
  { version: 82, date: '2026-07-20', summary: 'Adicionar submenu no e-mail (Exportar dados + Sair) com exportação de backup em JSON' },
  { version: 81, date: '2026-07-20', summary: 'Hábitos inicia retraído, Meu Dia inicia expandido' },
  { version: 80, date: '2026-07-20', summary: 'Hábitos: fonte esmaecida quando marcado/saltado (como Starting Day); reduzir espaçamento das listas' },
  { version: 79, date: '2026-07-20', summary: 'Hábitos: cor pastel vermelho pro saltado, rótulos restaurados, junta HubSpot no resumo e inclui hábitos no total Geral' },
  { version: 78, date: '2026-07-20', summary: 'Hábitos: checkbox único marca o dia de hoje, remove rótulo \'A evitar\', quadradinhos sempre verdes quando feitos' },
  { version: 77, date: '2026-07-20', summary: 'Corrigir tela em branco: mesclar cache local antigo com os defaults da seed antes do primeiro render' },
  { version: 76, date: '2026-07-20', summary: 'Adicionar retrair/expandir no Meu Dia e nova sessão de Hábitos (bons e a evitar) com sequência de 7 dias, edição e contadores' },
  { version: 75, date: '2026-07-19', summary: 'Desfazer v74; aplicar fonte do Agenda de Hoje nos títulos do resumo do topo' },
  { version: 74, date: '2026-07-19', summary: 'Unificar fonte dos títulos dos cards com o padrão do Agenda de Hoje' },
  { version: 73, date: '2026-07-19', summary: 'Só usar x-success (retorno automático) no iOS; evita aba extra do Chrome no Mac' },
  { version: 72, date: '2026-07-19', summary: 'Corrigir loop infinito do auto-sync de Lembretes ao voltar do Atalho em janela nova' },
  { version: 71, date: '2026-07-19', summary: 'Remover instrumentação de debug do badge; ocultar botão de notificações quando já concedida' },
  { version: 70, date: '2026-07-19', summary: 'Pedir permissão de notificação via toque no botão (iOS exige gesto do usuário)' },
  { version: 69, date: '2026-07-19', summary: 'Solicitar permissão de notificação para destravar badge no iOS' },
  { version: 68, date: '2026-07-19', summary: 'Diagnóstico do badge agora ignora a chamada inicial de clear' },
  { version: 67, date: '2026-07-19', summary: 'Diagnóstico temporário do badge do app' },
  { version: 66, date: '2026-07-19', summary: 'Mensagem de carregamento fica verde e maior' },
  { version: 65, date: '2026-07-19', summary: 'Adiciona mensagem \'Carregando informações...\' entre a data e o horário' },
  { version: 64, date: '2026-07-19', summary: 'Corrige captura do baseline saindo antes do Notion terminar' },
  { version: 63, date: '2026-07-19', summary: 'Corrige o baseline capturado antes da sincronização de Lembretes terminar' },
  { version: 62, date: '2026-07-19', summary: 'Remove o gate das 17:30 do Ending Day no Geral' },
  { version: 61, date: '2026-07-19', summary: 'Adiciona gatilho manual ?forceReset=1 pra reforçar reset e baseline' },
  { version: 60, date: '2026-07-18', summary: 'Remove o total do Starting Day e Ending Day no resumo' },
  { version: 59, date: '2026-07-18', summary: 'Preenchimento da barra de progresso passa a ser verde' },
  { version: 58, date: '2026-07-18', summary: 'Reinicia a checklist \'Ending Week\' toda sexta às 14h' },
  { version: 57, date: '2026-07-18', summary: 'Adiciona checklist \'Ending Week\' na segunda coluna' },
  { version: 56, date: '2026-07-18', summary: 'Aumenta o anel e a fonte do percentual no card Geral' },
  { version: 55, date: '2026-07-18', summary: 'Adiciona anel de progresso dentro do card Geral' },
  { version: 54, date: '2026-07-18', summary: 'Restringe a barra de progresso ao bloco de resumo do Hoje' },
  { version: 53, date: '2026-07-18', summary: 'Corrige o layout quebrado da barra de progresso do dia' },
  { version: 52, date: '2026-07-18', summary: 'Move a barra de progresso do dia para logo abaixo do resumo' },
  { version: 51, date: '2026-07-18', summary: 'Torna a barra de progresso do dia sempre visível e mais robusta' },
  { version: 50, date: '2026-07-18', summary: 'Adiciona barra de progresso do dia, fixa no rodapé' },
  { version: 49, date: '2026-07-18', summary: 'Sincroniza Lembretes ao abrir o dashboard, cor de atraso e reorganiza o resumo' },
  { version: 48, date: '2026-07-18', summary: 'Faz o refresh dos Lembretes reagir sozinho após o Atalho terminar' },
  { version: 47, date: '2026-07-18', summary: 'Consolida sincronizar+atualizar dos Lembretes, ajusta títulos e remove refresh do Meu Dia' },
  { version: 46, date: '2026-07-18', summary: 'Consolida os dois blocos de Lembretes em um só, agrupado' },
  { version: 45, date: '2026-07-18', summary: 'Links do Hubspot apontam para as views \'Meu Dia\' e \'Sem tarefa\' (Board)' },
  { version: 44, date: '2026-07-18', summary: 'Links do Hubspot abrem em nova aba, remove indicador ✅ do cabeçalho' },
  { version: 43, date: '2026-07-18', summary: 'Limpa dados ao atualizar e adiciona link Hubspot nos blocos de tarefas/deals' },
  { version: 42, date: '2026-07-18', summary: 'TickTick: link da tarefa tenta abrir no app (ticktick://) em vez do navegador' },
  { version: 41, date: '2026-07-18', summary: 'TickTick: inclui a Caixa de Entrada (via id especial "inbox") no bloco de tarefas, e limpa a instrumentação de debug já resolvida' },
  { version: 40, date: '2026-07-18', summary: 'TickTick debug: testa o id especial "inbox" para a Caixa de Entrada, que não aparece na listagem normal de projetos' },
  { version: 39, date: '2026-07-18', summary: 'TickTick debug: testa parâmetro de limite/paginação para confirmar se os 99 itens são um teto rígido da API' },
  { version: 38, date: '2026-07-18', summary: 'TickTick debug: conta quantas tarefas passam em cada filtro e permite buscar uma tarefa específica por título' },
  { version: 37, date: '2026-07-18', summary: 'TickTick: adiciona modo debug para inspecionar dados brutos de um projeto específico' },
  { version: 36, date: '2026-07-18', summary: 'Erro de configuração do callback do TickTick agora lista exatamente quais variáveis de ambiente estão faltando' },
  { version: 35, date: '2026-07-18', summary: 'Adiciona integração real com TickTick (OAuth2, tarefas vencidas/hoje agrupadas por lista, botão do app, contrair/expandir) e generaliza o card de tarefas agrupadas para Notion + TickTick' },
  { version: 34, date: '2026-07-18', summary: 'Perguntar antes de reiniciar Starting Day/Ending Day no primeiro carregamento do dia' },
  { version: 33, date: '2026-07-18', summary: 'Notion: agrupar tarefas usando a relação reversa da base Projetos ("[A] Atividades"), já que a relação direta da tarefa é pouco confiável via API' },
  { version: 32, date: '2026-07-18', summary: 'Debug: inspecionar diretamente a base Projetos (schema + amostra), já que a propriedade não pertence ao schema da base de tarefas' },
  { version: 31, date: '2026-07-18', summary: 'Debug: corrige comparação de schema por nome em vez de id (o id vinha em formatos diferentes entre os dois endpoints), com dump de todos os tipos como rede de segurança' },
  { version: 30, date: '2026-07-18', summary: 'Debug: incluir a definição do schema da propriedade de projeto (detecta relação sincronizada/dual-property)' },
  { version: 29, date: '2026-07-18', summary: 'Debug: permite escolher a tarefa testada via ?title= em vez de sempre a primeira' },
  { version: 28, date: '2026-07-18', summary: 'Debug: expor status/corpo cru da chamada de property item, em vez de engolir o erro silenciosamente' },
  { version: 27, date: '2026-07-18', summary: 'Notion: buscar o valor real da relação de projeto via endpoint dedicado, já que a query de database não retorna esse dado de forma confiável' },
  { version: 26, date: '2026-07-18', summary: 'Notion: modo debug agora rastreia a resolução completa do item principal (parent fallback) para diagnosticar o grupo "Sem Projeto"' },
  { version: 25, date: '2026-07-18', summary: 'Notion: agrupar tarefas por projeto (ordenado A-Z, tarefas A-Z dentro do grupo), como no bloco HubSpot; corrige filtro de data (comparação de calendário em vez de instante, evitando tarefas de amanhã aparecerem como vencidas)' },
  { version: 24, date: '2026-07-18', summary: 'Notion: busca o projeto no item principal quando o subitem não tem a relação diretamente' },
  { version: 23, date: '2026-07-18', summary: 'Renomeia botão da Agenda para "Calendário", corrige exclusão de status por gênero (Concluída/Cancelada), busca tolerante de propriedade Status, e adiciona modo debug ao endpoint do Notion' },
  { version: 22, date: '2026-07-18', summary: 'Corrige sufixo de projeto (relação) e link do Notion (abre no app), reduz fonte dos subtítulos do HubSpot, corrige edição do Meu Dia (cursor no meio do texto, tamanho sem salto) e adiciona cor cinza' },
  { version: 21, date: '2026-07-18', summary: 'Ajustes no bloco Notion: link posicionado na view Hoje, botão renomeado, título com hierarquia visual, e resolução de projeto via relação' },
  { version: 20, date: '2026-07-18', summary: 'Notion: botão para abrir a visão semanal no app, painel recolhível (inicia retraído), e sufixo [A] Projetos; Meu Dia: seletor de cor por post-it' },
  { version: 19, date: '2026-07-18', summary: 'Renomear bloco Notion e abrir tarefas em nova aba sem tirar o foco do dashboard' },
  { version: 18, date: '2026-07-18', summary: 'Corrigir título em branco nas tarefas do Notion (fallback para a propriedade real de título)' },
  { version: 17, date: '2026-07-18', summary: 'Excluir tarefas Concluído/Cancelado do bloco Notion - Hoje' },
  { version: 16, date: '2026-07-18', summary: 'Adicionar bloco Notion - Hoje com dados reais (vencidas + hoje, com hyperlink)' },
  { version: 15, date: '2026-07-18', summary: 'Adicionar botão de editar nota no Meu Dia, ao lado do X' },
];
